import { img, banner, P, type RestaurantInput } from './helpers'

export const bangaloreRestaurants: RestaurantInput[] = [
  {
    name: "McDonald's",
    slug: 'mcdonalds-koramangala',
    description: "America's favourite burgers, now hotter and faster than ever.",
    imageUrl: img(P.burger),
    bannerUrl: banner(P.burger),
    cuisines: ['Burgers', 'Fast Food', 'American'],
    rating: 4.3, ratingCount: 12400, avgDeliveryTime: 25, deliveryFee: 0, minOrderAmount: 99,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Koramangala', address: '100 Feet Road, Koramangala, Bangalore',
    menu: [
      { name: 'Burgers', items: [
        { name: 'McAloo Tikki', price: 59, isVeg: true, description: 'Crispy potato and peas patty with tangy sauce', isBestSeller: true, imageId: P.burger },
        { name: 'McVeggie', price: 79, isVeg: true, description: 'Vegetable patty with special sauce and lettuce', imageId: P.burger },
        { name: 'McChicken', price: 99, isVeg: false, description: 'Crispy chicken patty with mayo and mustard', isBestSeller: true, imageId: P.burger2 },
        { name: 'McSpicy Chicken', price: 149, isVeg: false, description: 'Spicy chicken fillet with jalapeño and cheese', imageId: P.burger2 },
        { name: 'Maharaja Mac', price: 169, isVeg: false, description: 'Double chicken patty with special sauce', isBestSeller: true, imageId: P.burger2 },
      ]},
      { name: 'Wraps & Sides', items: [
        { name: 'Spicy Paneer Wrap', price: 129, isVeg: true, description: 'Grilled paneer with veggies and chipotle sauce', imageId: P.roll },
        { name: 'McSaver Fries (M)', price: 69, isVeg: true, description: 'Golden crispy fries', isBestSeller: true, imageId: P.fries },
        { name: 'McSaver Fries (L)', price: 89, isVeg: true, imageId: P.fries },
        { name: 'Hash Brown', price: 49, isVeg: true, description: 'Crispy golden hash brown', imageId: P.fries },
      ]},
      { name: 'Beverages & Desserts', items: [
        { name: 'McCafé Latte', price: 99, isVeg: true, imageId: P.coffee },
        { name: 'Chocolate Shake', price: 89, isVeg: true, isBestSeller: true, imageId: P.dessert },
        { name: 'McFlurry Oreo', price: 79, isVeg: true, imageId: P.iceCream },
        { name: 'Soft Serve Cone', price: 29, isVeg: true, imageId: P.iceCream },
      ]},
    ],
  },
  {
    name: 'Meghana Foods',
    slug: 'meghana-foods-koramangala',
    description: 'Authentic Andhra biryani cooked in dum style with aromatic spices.',
    imageUrl: img(P.biryani),
    cuisines: ['Biryani', 'Andhra', 'South Indian'],
    rating: 4.5, ratingCount: 8900, avgDeliveryTime: 35, deliveryFee: 30, minOrderAmount: 150,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Koramangala', address: '71/72, Koramangala 4th Block, Bangalore',
    menu: [
      { name: 'Biryani', items: [
        { name: 'Chicken Biryani (Half)', price: 199, isVeg: false, description: 'Aromatic dum chicken biryani — half portion', isBestSeller: true, imageId: P.biryani },
        { name: 'Chicken Biryani (Full)', price: 349, isVeg: false, description: 'Aromatic dum chicken biryani — full portion', imageId: P.biryani },
        { name: 'Mutton Biryani (Half)', price: 249, isVeg: false, description: 'Slow-cooked dum mutton biryani', isBestSeller: true, imageId: P.biryani2 },
        { name: 'Veg Biryani (Half)', price: 149, isVeg: true, description: 'Mixed vegetables in fragrant basmati rice', imageId: P.biryani },
      ]},
      { name: 'Starters', items: [
        { name: 'Chicken 65', price: 189, isVeg: false, description: 'Spicy deep-fried chicken — Andhra style', isBestSeller: true, imageId: P.chicken },
        { name: 'Gobi Manchurian', price: 149, isVeg: true, imageId: P.chinese },
        { name: 'Fish Fry', price: 229, isVeg: false, imageId: P.seafood },
        { name: 'Paneer 65', price: 169, isVeg: true, imageId: P.northIndian },
      ]},
      { name: 'Curries & Dal', items: [
        { name: 'Dal Tadka', price: 129, isVeg: true, imageId: P.curry },
        { name: 'Chicken Curry', price: 199, isVeg: false, imageId: P.curry },
        { name: 'Paneer Butter Masala', price: 179, isVeg: true, isBestSeller: true, imageId: P.northIndian },
      ]},
    ],
  },
  {
    name: 'Pizza Hut',
    slug: 'pizza-hut-indiranagar',
    description: 'Pan pizzas, stuffed crust, and more — made fresh to your order.',
    imageUrl: img(P.pizza),
    cuisines: ['Pizza', 'Italian', 'Fast Food'],
    rating: 4.1, ratingCount: 6300, avgDeliveryTime: 40, deliveryFee: 40, minOrderAmount: 199,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Indiranagar', address: '100 Feet Road, Indiranagar, Bangalore',
    menu: [
      { name: 'Pan Pizzas', items: [
        { name: 'Margherita (M)', price: 249, isVeg: true, description: 'Classic tomato sauce and mozzarella', isBestSeller: true, imageId: P.pizza },
        { name: 'Veg Supreme (M)', price: 399, isVeg: true, description: 'Loaded with farm-fresh veggies', imageId: P.pizza },
        { name: 'Chicken Supreme (M)', price: 449, isVeg: false, description: 'Grilled chicken with BBQ sauce', isBestSeller: true, imageId: P.pizza2 },
        { name: 'BBQ Chicken (L)', price: 649, isVeg: false, imageId: P.pizza2 },
      ]},
      { name: 'Pastas & Sides', items: [
        { name: 'Mac n Cheese Pasta', price: 199, isVeg: true, isBestSeller: true, imageId: P.pasta },
        { name: 'Chicken Fiesta Pasta', price: 229, isVeg: false, imageId: P.pasta },
        { name: 'Garlic Bread', price: 99, isVeg: true, description: 'Toasted with herb butter', imageId: P.bread },
        { name: 'Stuffed Garlic Bread', price: 149, isVeg: true, imageId: P.bread },
      ]},
      { name: 'Desserts & Drinks', items: [
        { name: 'Choco Lava Cake', price: 89, isVeg: true, isBestSeller: true, imageId: P.dessert },
        { name: 'Pepsi (M)', price: 49, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Saravanaa Bhavan',
    slug: 'saravanaa-bhavan-btm',
    description: "South India's iconic pure vegetarian restaurant.",
    imageUrl: img(P.dosa),
    cuisines: ['South Indian', 'Tiffin', 'North Indian'],
    rating: 4.6, ratingCount: 15200, avgDeliveryTime: 30, deliveryFee: 0, minOrderAmount: 100,
    isOpen: true, isPureVeg: true,
    city: 'Bangalore', area: 'BTM Layout', address: '14th Cross, BTM 2nd Stage, Bangalore',
    menu: [
      { name: 'Breakfast', items: [
        { name: 'Masala Dosa', price: 89, isVeg: true, description: 'Crispy dosa with spiced potato filling', isBestSeller: true, imageId: P.dosa },
        { name: 'Idli Sambar (3 pcs)', price: 69, isVeg: true, imageId: P.idli },
        { name: 'Rava Dosa', price: 99, isVeg: true, isBestSeller: true, imageId: P.dosa },
        { name: 'Uttapam', price: 89, isVeg: true, imageId: P.dosa },
        { name: 'Poori Masala', price: 79, isVeg: true, imageId: P.bread },
      ]},
      { name: 'Meals', items: [
        { name: 'Thali (Full Meals)', price: 149, isVeg: true, description: 'Rice, sambar, rasam, curries, and dessert', isBestSeller: true, imageId: P.thali },
        { name: 'Mini Meals', price: 99, isVeg: true, imageId: P.thali },
      ]},
      { name: 'Beverages', items: [
        { name: 'Filter Coffee', price: 49, isVeg: true, isBestSeller: true, imageId: P.coffee },
        { name: 'Lassi', price: 59, isVeg: true, imageId: P.drinks },
        { name: 'Buttermilk', price: 39, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Behrouz Biryani',
    slug: 'behrouz-biryani-whitefield',
    description: 'Royal dum biryanis inspired by Persian culinary traditions.',
    imageUrl: img(P.biryani3),
    bannerUrl: banner(P.biryani3),
    cuisines: ['Biryani', 'Mughlai', 'Persian'],
    rating: 4.4, ratingCount: 9800, avgDeliveryTime: 45, deliveryFee: 50, minOrderAmount: 250,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Whitefield', address: 'Prestige Tech Park, Whitefield, Bangalore',
    menu: [
      { name: 'Dum Biryani', items: [
        { name: 'The Behrouz Biryani (Chicken)', price: 349, isVeg: false, description: 'Slow-cooked dum chicken biryani in royal Persian style', isBestSeller: true, imageId: P.biryani3 },
        { name: 'The Behrouz Biryani (Mutton)', price: 449, isVeg: false, description: 'Tender mutton pieces in saffron-infused basmati', isBestSeller: true, imageId: P.biryani2 },
        { name: 'Murgh Mussallam Biryani', price: 399, isVeg: false, description: 'Whole chicken marinated in aromatic spices', imageId: P.biryani },
        { name: 'Navratan Biryani', price: 279, isVeg: true, description: 'Nine jewels of vegetables in fragrant basmati', imageId: P.biryani },
      ]},
      { name: 'Sides & Curries', items: [
        { name: 'Burhani Raita', price: 79, isVeg: true, description: 'Chilled yogurt with mint and jeera', imageId: P.veg },
        { name: 'Murgh Peshwari Korma', price: 249, isVeg: false, description: 'Tender chicken in rich Peshwari gravy', imageId: P.curry },
        { name: 'Shahi Paneer', price: 229, isVeg: true, imageId: P.northIndian },
      ]},
      { name: 'Beverages', items: [
        { name: 'Rose Sharbat', price: 79, isVeg: true, description: 'Chilled rose drink with basil seeds', imageId: P.drinks },
        { name: 'Mango Lassi', price: 99, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Chinese Wok',
    slug: 'chinese-wok-jp-nagar',
    description: 'Fresh and flavourful Indo-Chinese food made to order.',
    imageUrl: img(P.chinese),
    cuisines: ['Chinese', 'Indo-Chinese', 'Asian'],
    rating: 3.9, ratingCount: 4100, avgDeliveryTime: 30, deliveryFee: 25, minOrderAmount: 149,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'JP Nagar', address: '5th Phase, JP Nagar, Bangalore',
    menu: [
      { name: 'Noodles & Rice', items: [
        { name: 'Veg Hakka Noodles', price: 149, isVeg: true, isBestSeller: true, imageId: P.noodles },
        { name: 'Chicken Fried Rice', price: 169, isVeg: false, isBestSeller: true, imageId: P.friedRice },
        { name: 'Egg Fried Rice', price: 149, isVeg: false, imageId: P.friedRice },
        { name: 'Schezwan Noodles', price: 169, isVeg: true, imageId: P.noodles },
        { name: 'Singapore Noodles', price: 179, isVeg: false, imageId: P.noodles },
      ]},
      { name: 'Starters', items: [
        { name: 'Gobi Manchurian (Dry)', price: 149, isVeg: true, isBestSeller: true, imageId: P.chinese },
        { name: 'Chilli Chicken (Dry)', price: 179, isVeg: false, isBestSeller: true, imageId: P.chinese },
        { name: 'Veg Spring Rolls (4 pcs)', price: 99, isVeg: true, imageId: P.chinese },
        { name: 'Honey Chilli Potato', price: 129, isVeg: true, imageId: P.fries },
      ]},
    ],
  },
  {
    name: "Domino's Pizza",
    slug: 'dominos-pizza-jayanagar',
    description: "30 minutes or free — India's #1 pizza delivery brand.",
    imageUrl: img(P.pizza2),
    cuisines: ['Pizza', 'Pasta', 'Fast Food'],
    rating: 4.0, ratingCount: 22000, avgDeliveryTime: 30, deliveryFee: 0, minOrderAmount: 149,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Jayanagar', address: '4th Block, Jayanagar, Bangalore',
    menu: [
      { name: 'Pizzas', items: [
        { name: 'Margherita (M)', price: 199, isVeg: true, description: 'Classic tomato sauce and mozzarella', isBestSeller: true, imageId: P.pizza2 },
        { name: 'Peppy Paneer (M)', price: 299, isVeg: true, description: 'Chunky paneer with capsicum and onion', isBestSeller: true, imageId: P.pizza },
        { name: 'Chicken Pepperoni (M)', price: 349, isVeg: false, description: 'Spicy chicken pepperoni slices', imageId: P.pizza2 },
        { name: 'Double Cheese Margarita (L)', price: 499, isVeg: true, imageId: P.pizza },
        { name: 'Chicken Fiesta (L)', price: 549, isVeg: false, isBestSeller: true, imageId: P.pizza2 },
      ]},
      { name: 'Sides', items: [
        { name: 'Garlic Breadsticks', price: 79, isVeg: true, isBestSeller: true, imageId: P.bread },
        { name: 'Stuffed Garlic Bread', price: 149, isVeg: true, imageId: P.bread },
        { name: 'Pasta Italiana (Veg)', price: 149, isVeg: true, imageId: P.pasta },
        { name: 'Chicken Wings (6 pcs)', price: 169, isVeg: false, imageId: P.chicken },
      ]},
      { name: 'Desserts', items: [
        { name: 'Choco Lava Cake', price: 89, isVeg: true, isBestSeller: true, imageId: P.dessert },
        { name: 'Pepsi (M)', price: 49, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Burger King',
    slug: 'burger-king-mg-road',
    description: 'Have it your way — flame-grilled burgers with real flavour.',
    imageUrl: img(P.burger2),
    cuisines: ['Burgers', 'Fast Food', 'American'],
    rating: 4.2, ratingCount: 7800, avgDeliveryTime: 28, deliveryFee: 30, minOrderAmount: 99,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'MG Road', address: 'Brigade Road, MG Road, Bangalore',
    menu: [
      { name: 'Burgers', items: [
        { name: 'Veg Whopper', price: 149, isVeg: true, description: 'Flame-grilled veggie patty with fresh veggies', isBestSeller: true, imageId: P.burger },
        { name: 'Chicken Whopper', price: 189, isVeg: false, description: 'Flame-grilled chicken with lettuce and tomato', isBestSeller: true, imageId: P.burger2 },
        { name: 'Crispy Veg Burger', price: 99, isVeg: true, imageId: P.burger },
        { name: 'Double Chicken Burger', price: 219, isVeg: false, imageId: P.burger2 },
        { name: 'Cheesy Bacon Chicken', price: 249, isVeg: false, description: 'Chicken patty, cheddar, crispy bacon', imageId: P.burger2 },
      ]},
      { name: 'Combos & Sides', items: [
        { name: 'Veg Whopper Meal', price: 249, isVeg: true, description: 'Burger + fries + drink', isBestSeller: true, imageId: P.burger },
        { name: 'Chicken Whopper Meal', price: 299, isVeg: false, isBestSeller: true, imageId: P.burger2 },
        { name: 'French Fries (M)', price: 89, isVeg: true, imageId: P.fries },
        { name: 'Onion Rings', price: 79, isVeg: true, imageId: P.fries },
      ]},
      { name: 'Beverages & Desserts', items: [
        { name: 'Hershey\'s Chocolate Shake', price: 129, isVeg: true, isBestSeller: true, imageId: P.dessert },
        { name: 'Mango Smoothie', price: 99, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: "La Pino'z Pizza",
    slug: 'la-pinoz-pizza-hsr',
    description: 'Hand-tossed, stone-baked pizzas with fresh toppings and rich sauces.',
    imageUrl: img(P.pizza),
    bannerUrl: banner(P.pizza),
    cuisines: ['Pizza', 'Italian', 'Fast Food'],
    rating: 4.3, ratingCount: 5400, avgDeliveryTime: 35, deliveryFee: 30, minOrderAmount: 199,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'HSR Layout', address: '27th Main, HSR Layout, Bangalore',
    menu: [
      { name: 'Pizzas', items: [
        { name: 'Margherita (M)', price: 249, isVeg: true, isBestSeller: true, imageId: P.pizza },
        { name: 'Four Cheese (M)', price: 349, isVeg: true, description: 'Mozzarella, cheddar, gouda, parmesan', isBestSeller: true, imageId: P.pizza2 },
        { name: 'Farmhouse (M)', price: 299, isVeg: true, description: 'Capsicum, onion, mushroom, sweet corn', imageId: P.pizza },
        { name: 'BBQ Chicken (M)', price: 399, isVeg: false, description: 'Smoky BBQ with tender chicken chunks', isBestSeller: true, imageId: P.pizza2 },
        { name: 'Peri Peri Chicken (L)', price: 549, isVeg: false, description: 'Fiery peri peri sauce with grilled chicken', imageId: P.pizza2 },
      ]},
      { name: 'Sides & Dips', items: [
        { name: 'Garlic Bread with Cheese', price: 149, isVeg: true, isBestSeller: true, imageId: P.bread },
        { name: 'Stuffed Garlic Breadsticks', price: 179, isVeg: true, imageId: P.bread },
        { name: 'Cheesy Dip', price: 49, isVeg: true, imageId: P.veg },
      ]},
      { name: 'Drinks', items: [
        { name: 'Pepsi (L)', price: 69, isVeg: true, imageId: P.drinks },
        { name: 'Virgin Mojito', price: 99, isVeg: true, isBestSeller: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Paradise Biryani',
    slug: 'paradise-biryani-marathahalli',
    description: "Hyderabad's legendary dum biryani, now in Bangalore.",
    imageUrl: img(P.biryani2),
    bannerUrl: banner(P.biryani2),
    cuisines: ['Biryani', 'Hyderabadi', 'Mughlai'],
    rating: 4.5, ratingCount: 11200, avgDeliveryTime: 40, deliveryFee: 35, minOrderAmount: 199,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Marathahalli', address: 'Outer Ring Road, Marathahalli, Bangalore',
    menu: [
      { name: 'Biryani', items: [
        { name: 'Chicken Dum Biryani (Half)', price: 219, isVeg: false, description: 'Aromatic dum-cooked chicken biryani', isBestSeller: true, imageId: P.biryani2 },
        { name: 'Chicken Dum Biryani (Full)', price: 389, isVeg: false, isBestSeller: true, imageId: P.biryani },
        { name: 'Mutton Dum Biryani (Half)', price: 279, isVeg: false, imageId: P.biryani2 },
        { name: 'Prawn Biryani', price: 319, isVeg: false, description: 'Juicy prawns in spiced basmati', imageId: P.seafood },
        { name: 'Veg Dum Biryani', price: 179, isVeg: true, imageId: P.biryani },
      ]},
      { name: 'Starters', items: [
        { name: 'Chicken 65', price: 199, isVeg: false, isBestSeller: true, imageId: P.chicken },
        { name: 'Seekh Kebab (4 pcs)', price: 249, isVeg: false, imageId: P.kebab },
        { name: 'Veg Shammi Kebab', price: 179, isVeg: true, imageId: P.northIndian },
      ]},
      { name: 'Accompaniments', items: [
        { name: 'Raita', price: 49, isVeg: true, imageId: P.veg },
        { name: 'Mirchi Ka Salan', price: 59, isVeg: true, imageId: P.curry },
      ]},
    ],
  },
  {
    name: 'The Burger Lab',
    slug: 'the-burger-lab-hsr',
    description: 'Gourmet smash burgers with premium patties and house-made sauces.',
    imageUrl: img(P.burger),
    bannerUrl: banner(P.burger),
    cuisines: ['Burgers', 'American', 'Fast Food'],
    rating: 4.4, ratingCount: 3800, avgDeliveryTime: 28, deliveryFee: 40, minOrderAmount: 149,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'HSR Layout', address: 'Sector 2, HSR Layout, Bangalore',
    menu: [
      { name: 'Classic Burgers', items: [
        { name: 'Crispy Veg Burger', price: 99, isVeg: true, description: 'Crispy veggie patty with house mayo', isBestSeller: true, imageId: P.burger },
        { name: 'Classic Chicken Burger', price: 149, isVeg: false, description: 'Juicy chicken patty with house sauce', isBestSeller: true, imageId: P.burger2 },
        { name: 'Mushroom Swiss Burger', price: 179, isVeg: true, description: 'Sautéed mushrooms with Swiss cheese', imageId: P.burger },
        { name: 'Double Smash Burger', price: 219, isVeg: false, description: 'Two smash patties with caramelised onions', imageId: P.burger2 },
      ]},
      { name: 'Loaded Burgers', items: [
        { name: 'Bacon BBQ Tower', price: 299, isVeg: false, description: 'Double patty, bacon, BBQ sauce, cheddar', isBestSeller: true, imageId: P.burger2 },
        { name: 'Truffle Mushroom Burger', price: 249, isVeg: true, description: 'Truffle aioli, portobello mushroom, arugula', imageId: P.burger },
        { name: 'Spicy Sriracha Chicken', price: 269, isVeg: false, imageId: P.burger2 },
      ]},
      { name: 'Sides & Drinks', items: [
        { name: 'Loaded Cheese Fries', price: 149, isVeg: true, isBestSeller: true, imageId: P.fries },
        { name: 'Onion Rings', price: 119, isVeg: true, imageId: P.fries },
        { name: 'Chocolate Milkshake', price: 149, isVeg: true, imageId: P.dessert },
      ]},
    ],
  },
  {
    name: 'Mainland China',
    slug: 'mainland-china-ub-city',
    description: 'Fine-dining Chinese cuisine with authentic Cantonese and Sichuan flavours.',
    imageUrl: img(P.chinese),
    bannerUrl: banner(P.chinese),
    cuisines: ['Chinese', 'Asian', 'Cantonese'],
    rating: 4.3, ratingCount: 6700, avgDeliveryTime: 45, deliveryFee: 50, minOrderAmount: 299,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'UB City', address: 'UB City Mall, Vittal Mallya Road, Bangalore',
    menu: [
      { name: 'Dimsums', items: [
        { name: 'Crystal Veg Dumpling (4 pcs)', price: 199, isVeg: true, description: 'Translucent skin, water chestnut, greens', isBestSeller: true, imageId: P.momos },
        { name: 'Chicken Dimsum (4 pcs)', price: 229, isVeg: false, description: 'Steamed chicken and prawn dumplings', isBestSeller: true, imageId: P.momos },
        { name: 'Prawn Har Gao (4 pcs)', price: 249, isVeg: false, description: 'Classic Cantonese prawn dumplings', imageId: P.momos },
      ]},
      { name: 'Mains', items: [
        { name: 'Kung Pao Chicken', price: 349, isVeg: false, description: 'Wok-tossed with peanuts and dried chillies', isBestSeller: true, imageId: P.chinese },
        { name: 'Crispy Baby Corn', price: 279, isVeg: true, description: 'Battered baby corn in Sichuan sauce', imageId: P.chinese },
        { name: 'Mapo Tofu', price: 269, isVeg: true, description: 'Silken tofu in spicy fermented bean sauce', imageId: P.chinese },
        { name: 'Chilli Garlic Prawns', price: 399, isVeg: false, imageId: P.seafood },
      ]},
      { name: 'Noodles & Rice', items: [
        { name: 'Wok-Tossed Hakka Noodles', price: 249, isVeg: true, isBestSeller: true, imageId: P.noodles },
        { name: 'Singapore Fried Rice', price: 279, isVeg: false, imageId: P.friedRice },
        { name: 'Schezwan Fried Noodles', price: 249, isVeg: true, imageId: P.noodles },
      ]},
    ],
  },
  {
    name: 'MTR 1924',
    slug: 'mtr-1924-lalbagh',
    description: "Bangalore's oldest and most iconic pure vegetarian South Indian restaurant.",
    imageUrl: img(P.idli),
    bannerUrl: banner(P.idli),
    cuisines: ['South Indian', 'Tiffin', 'Breakfast'],
    rating: 4.7, ratingCount: 19500, avgDeliveryTime: 30, deliveryFee: 0, minOrderAmount: 99,
    isOpen: true, isPureVeg: true,
    city: 'Bangalore', area: 'Lalbagh', address: '11 Lalbagh Road, Mavalli, Bangalore',
    menu: [
      { name: 'Tiffin', items: [
        { name: 'Masala Dosa', price: 95, isVeg: true, description: 'Crispy dosa with spiced potato filling', isBestSeller: true, imageId: P.dosa },
        { name: 'Idli Sambar (2 pcs)', price: 65, isVeg: true, description: 'Fluffy steamed idlis with MTR sambar', isBestSeller: true, imageId: P.idli },
        { name: 'Rava Idli (3 pcs)', price: 85, isVeg: true, description: 'Semolina idlis garnished with cashews', imageId: P.idli },
        { name: 'Set Dosa (3 pcs)', price: 89, isVeg: true, description: 'Soft spongy dosas with coconut chutney', imageId: P.dosa },
      ]},
      { name: 'Meals', items: [
        { name: 'MTR Special Thali', price: 199, isVeg: true, description: 'Rice, sambar, rasam, 3 curries, papad and dessert', isBestSeller: true, imageId: P.thali },
        { name: 'Mini Meals', price: 149, isVeg: true, description: 'Rice, sambar, rasam and 2 curries', imageId: P.thali },
        { name: 'Curd Rice', price: 79, isVeg: true, description: 'Cooling curd rice with pickle', imageId: P.veg },
      ]},
      { name: 'Beverages', items: [
        { name: 'MTR Filter Coffee', price: 45, isVeg: true, description: 'Strong South Indian decoction with hot milk', isBestSeller: true, imageId: P.coffee },
        { name: 'Badam Milk', price: 79, isVeg: true, imageId: P.drinks },
        { name: 'Rose Milk', price: 55, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'The Belgian Waffle Co.',
    slug: 'belgian-waffle-co-indiranagar',
    description: 'Freshly made Belgian waffles, crepes, and desserts with indulgent toppings.',
    imageUrl: img(P.waffle),
    bannerUrl: banner(P.waffle),
    cuisines: ['Desserts', 'Waffles', 'Bakery'],
    rating: 4.2, ratingCount: 7100, avgDeliveryTime: 25, deliveryFee: 30, minOrderAmount: 149,
    isOpen: true, isPureVeg: true,
    city: 'Bangalore', area: 'Indiranagar', address: '12th Main, Indiranagar, Bangalore',
    menu: [
      { name: 'Waffles', items: [
        { name: 'Classic Belgian Waffle', price: 149, isVeg: true, description: 'Light and crispy with maple syrup', isBestSeller: true, imageId: P.waffle },
        { name: 'Nutella Banana Waffle', price: 199, isVeg: true, description: 'Nutella, banana slices, cream', isBestSeller: true, imageId: P.dessert },
        { name: 'Red Velvet Waffle', price: 219, isVeg: true, imageId: P.dessert },
        { name: 'Lotus Biscoff Waffle', price: 229, isVeg: true, imageId: P.dessert },
      ]},
      { name: 'Crepes & Pancakes', items: [
        { name: 'Nutella Crepe', price: 169, isVeg: true, description: 'Thin crepe filled with Nutella and strawberries', isBestSeller: true, imageId: P.waffle },
        { name: 'Mixed Berry Crepe', price: 179, isVeg: true, imageId: P.dessert },
        { name: 'Fluffy Pancake Stack (3)', price: 189, isVeg: true, description: 'Three thick pancakes with butter and honey', imageId: P.waffle },
      ]},
      { name: 'Beverages', items: [
        { name: 'Hot Belgian Chocolate', price: 129, isVeg: true, imageId: P.coffee },
        { name: 'Cold Coffee', price: 119, isVeg: true, isBestSeller: true, imageId: P.coffee },
        { name: 'Mango Smoothie', price: 139, isVeg: true, imageId: P.drinks },
      ]},
    ],
  },
  {
    name: 'Kathi Junction',
    slug: 'kathi-junction-electronic-city',
    description: 'Rolled up goodness — Kolkata-style kathi rolls packed with flavour.',
    imageUrl: img(P.roll),
    bannerUrl: banner(P.roll),
    cuisines: ['Rolls', 'Kathi Roll', 'Street Food'],
    rating: 3.9, ratingCount: 2900, avgDeliveryTime: 25, deliveryFee: 20, minOrderAmount: 99,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Electronic City', address: 'Phase 1, Electronic City, Bangalore',
    menu: [
      { name: 'Veg Rolls', items: [
        { name: 'Paneer Kathi Roll', price: 129, isVeg: true, description: 'Spiced paneer tikka wrapped in a paratha', isBestSeller: true, imageId: P.roll },
        { name: 'Aloo Tikki Roll', price: 99, isVeg: true, description: 'Crispy potato tikki with mint chutney', imageId: P.roll },
        { name: 'Mixed Veg Roll', price: 109, isVeg: true, imageId: P.roll },
      ]},
      { name: 'Non-Veg Rolls', items: [
        { name: 'Chicken Kathi Roll', price: 149, isVeg: false, description: 'Juicy chicken tikka in a flaky paratha', isBestSeller: true, imageId: P.roll },
        { name: 'Egg Roll', price: 99, isVeg: false, description: 'Classic Kolkata-style egg roll', imageId: P.egg },
        { name: 'Chicken Seekh Roll', price: 159, isVeg: false, isBestSeller: true, imageId: P.kebab },
        { name: 'Mutton Roll', price: 179, isVeg: false, imageId: P.kebab },
      ]},
      { name: 'Sides', items: [
        { name: 'Masala Fries', price: 79, isVeg: true, isBestSeller: true, imageId: P.fries },
        { name: 'Mint Chutney', price: 29, isVeg: true, imageId: P.veg },
      ]},
    ],
  },
  {
    name: 'Trattoria',
    slug: 'trattoria-whitefield',
    description: 'Rustic Italian trattoria serving hand-crafted pasta and risotto.',
    imageUrl: img(P.pasta),
    bannerUrl: banner(P.pasta),
    cuisines: ['Pasta', 'Italian', 'Continental'],
    rating: 4.3, ratingCount: 4200, avgDeliveryTime: 40, deliveryFee: 45, minOrderAmount: 249,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Whitefield', address: 'ITPL Main Road, Whitefield, Bangalore',
    menu: [
      { name: 'Pasta', items: [
        { name: 'Spaghetti Aglio e Olio', price: 229, isVeg: true, description: 'Garlic, olive oil and chilli flakes', isBestSeller: true, imageId: P.pasta },
        { name: 'Penne Arrabbiata', price: 219, isVeg: true, description: 'Penne in spicy tomato sauce', imageId: P.pasta },
        { name: 'Fettuccine Alfredo', price: 249, isVeg: true, description: 'Creamy parmesan sauce', isBestSeller: true, imageId: P.pasta },
        { name: 'Chicken Bolognese', price: 299, isVeg: false, description: 'Slow-cooked chicken ragù over tagliatelle', isBestSeller: true, imageId: P.pasta },
      ]},
      { name: 'Risotto & Mains', items: [
        { name: 'Porcini Mushroom Risotto', price: 299, isVeg: true, description: 'Creamy arborio with porcini and truffle oil', isBestSeller: true, imageId: P.pasta },
        { name: 'Chicken Risotto', price: 339, isVeg: false, imageId: P.pasta },
        { name: 'Gnocchi Pomodoro', price: 279, isVeg: true, imageId: P.pasta },
      ]},
      { name: 'Starters', items: [
        { name: 'Garlic Ciabatta', price: 149, isVeg: true, isBestSeller: true, imageId: P.bread },
        { name: 'Caprese Salad', price: 199, isVeg: true, description: 'Fresh mozzarella, tomato and basil', imageId: P.veg },
      ]},
    ],
  },
  {
    name: 'Edo Japanese',
    slug: 'edo-japanese-mg-road',
    description: 'Authentic Tokyo-style sushi, nigiri, and Japanese small plates.',
    imageUrl: img(P.sushi),
    bannerUrl: banner(P.sushi),
    cuisines: ['Sushi', 'Japanese', 'Asian'],
    rating: 4.5, ratingCount: 3100, avgDeliveryTime: 45, deliveryFee: 60, minOrderAmount: 399,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'MG Road', address: 'Church Street, MG Road, Bangalore',
    menu: [
      { name: 'Nigiri & Sashimi', items: [
        { name: 'Salmon Nigiri (2 pcs)', price: 299, isVeg: false, description: 'Premium Atlantic salmon over seasoned rice', isBestSeller: true, imageId: P.sushi },
        { name: 'Tuna Sashimi (4 pcs)', price: 349, isVeg: false, description: 'Thinly sliced bluefin tuna', imageId: P.sushi },
        { name: 'Prawn Nigiri (2 pcs)', price: 249, isVeg: false, imageId: P.sushi },
      ]},
      { name: 'Rolls', items: [
        { name: 'California Roll (8 pcs)', price: 349, isVeg: false, description: 'Crab, avocado and cucumber', isBestSeller: true, imageId: P.sushi },
        { name: 'Spicy Tuna Roll (8 pcs)', price: 399, isVeg: false, isBestSeller: true, imageId: P.sushi },
        { name: 'Veggie Avocado Roll (8 pcs)', price: 299, isVeg: true, imageId: P.sushi },
        { name: 'Dragon Roll (8 pcs)', price: 449, isVeg: false, description: 'Prawn tempura topped with avocado', imageId: P.sushi },
      ]},
      { name: 'Sides', items: [
        { name: 'Miso Soup', price: 99, isVeg: true, description: 'Dashi miso with tofu and wakame', imageId: P.soup },
        { name: 'Edamame', price: 149, isVeg: true, imageId: P.veg },
        { name: 'Chicken Gyoza (4 pcs)', price: 199, isVeg: false, imageId: P.momos },
      ]},
    ],
  },
  {
    name: 'Momo Station',
    slug: 'momo-station-koramangala',
    description: 'Steamed, fried, and tandoori momos straight from the hills.',
    imageUrl: img(P.momos),
    bannerUrl: banner(P.momos),
    cuisines: ['Momos', 'Tibetan', 'Chinese'],
    rating: 4.1, ratingCount: 5800, avgDeliveryTime: 25, deliveryFee: 20, minOrderAmount: 99,
    isOpen: true, isPureVeg: false,
    city: 'Bangalore', area: 'Koramangala', address: '5th Block, Koramangala, Bangalore',
    menu: [
      { name: 'Steamed Momos', items: [
        { name: 'Veg Steamed Momos (8 pcs)', price: 89, isVeg: true, description: 'Classic steamed momos with cabbage and spices', isBestSeller: true, imageId: P.momos },
        { name: 'Chicken Steamed Momos (8 pcs)', price: 109, isVeg: false, isBestSeller: true, imageId: P.momos },
        { name: 'Paneer Steamed Momos (8 pcs)', price: 99, isVeg: true, imageId: P.momos },
      ]},
      { name: 'Fried & Tandoori Momos', items: [
        { name: 'Veg Fried Momos (8 pcs)', price: 99, isVeg: true, imageId: P.momos },
        { name: 'Chicken Fried Momos (8 pcs)', price: 119, isVeg: false, isBestSeller: true, imageId: P.momos },
        { name: 'Tandoori Chicken Momos (6 pcs)', price: 149, isVeg: false, description: 'Grilled in tandoor with smoky spice rub', isBestSeller: true, imageId: P.kebab },
        { name: 'Schezwan Fried Momos (8 pcs)', price: 119, isVeg: true, imageId: P.momos },
      ]},
      { name: 'Soups & Extras', items: [
        { name: 'Thukpa Soup', price: 119, isVeg: true, description: 'Tibetan noodle soup with vegetables', imageId: P.soup },
        { name: 'Chilli Momo (8 pcs)', price: 129, isVeg: false, imageId: P.momos },
      ]},
    ],
  },
  {
    name: 'Rajdhani Thali',
    slug: 'rajdhani-thali-malleswaram',
    description: 'Unlimited Gujarati-Rajasthani thali with rotating seasonal curries.',
    imageUrl: img(P.thali),
    bannerUrl: banner(P.thali),
    cuisines: ['Thali', 'Gujarati', 'Rajasthani'],
    rating: 4.4, ratingCount: 8900, avgDeliveryTime: 35, deliveryFee: 0, minOrderAmount: 199,
    isOpen: true, isPureVeg: true,
    city: 'Bangalore', area: 'Malleswaram', address: '8th Cross, Malleswaram, Bangalore',
    menu: [
      { name: 'Thali', items: [
        { name: 'Rajdhani Special Thali', price: 299, isVeg: true, description: 'Dal, 3 sabzis, rice, roti, papad, pickle and dessert', isBestSeller: true, imageId: P.thali },
        { name: 'Mini Thali', price: 199, isVeg: true, description: 'Dal, 2 sabzis, rice and 2 rotis', imageId: P.thali },
        { name: 'Premium Thali (Unlimited)', price: 399, isVeg: true, isBestSeller: true, imageId: P.thali },
      ]},
      { name: 'À La Carte', items: [
        { name: 'Dal Makhani', price: 149, isVeg: true, isBestSeller: true, imageId: P.curry },
        { name: 'Paneer Butter Masala', price: 179, isVeg: true, imageId: P.northIndian },
        { name: 'Aloo Gobhi', price: 129, isVeg: true, imageId: P.curry },
        { name: 'Jeera Rice', price: 99, isVeg: true, imageId: P.veg },
        { name: 'Butter Naan', price: 39, isVeg: true, isBestSeller: true, imageId: P.bread },
      ]},
      { name: 'Desserts', items: [
        { name: 'Gulab Jamun (2 pcs)', price: 69, isVeg: true, isBestSeller: true, imageId: P.sweets },
        { name: 'Kheer', price: 79, isVeg: true, description: 'Creamy rice pudding with cardamom and saffron', imageId: P.sweets },
      ]},
    ],
  },
  {
    name: 'Corner House Ice Cream',
    slug: 'corner-house-ice-cream-jayanagar',
    description: "Bangalore's beloved ice cream parlour since 1973 — legendary Death by Chocolate.",
    imageUrl: img(P.iceCream),
    bannerUrl: banner(P.iceCream),
    cuisines: ['Ice Cream', 'Desserts', 'Shakes'],
    rating: 4.6, ratingCount: 14300, avgDeliveryTime: 20, deliveryFee: 25, minOrderAmount: 99,
    isOpen: true, isPureVeg: true,
    city: 'Bangalore', area: 'Jayanagar', address: '298, 11th Main, Jayanagar 4th Block, Bangalore',
    menu: [
      { name: 'Sundaes', items: [
        { name: 'Death by Chocolate', price: 199, isVeg: true, description: 'Chocolate ice cream, hot fudge, brownie and cream', isBestSeller: true, imageId: P.dessert },
        { name: 'Hot Fudge Sundae', price: 169, isVeg: true, description: 'Vanilla ice cream with warm chocolate fudge', isBestSeller: true, imageId: P.iceCream },
        { name: 'Strawberry Delight', price: 149, isVeg: true, imageId: P.iceCream },
      ]},
      { name: 'Scoops & Cones', items: [
        { name: 'Single Scoop Cone', price: 79, isVeg: true, description: 'Choose from 20+ flavours', imageId: P.iceCream },
        { name: 'Double Scoop Cup', price: 129, isVeg: true, isBestSeller: true, imageId: P.iceCream },
        { name: 'Belgian Chocolate Scoop', price: 99, isVeg: true, imageId: P.dessert },
        { name: 'Waffle Cone (2 scoops)', price: 149, isVeg: true, imageId: P.iceCream },
      ]},
      { name: 'Shakes & More', items: [
        { name: 'Thick Chocolate Shake', price: 179, isVeg: true, isBestSeller: true, imageId: P.dessert },
        { name: 'Banana Split', price: 199, isVeg: true, description: 'Three scoops with banana, fudge and nuts', imageId: P.iceCream },
        { name: 'Ice Cream Sandwich', price: 129, isVeg: true, imageId: P.iceCream },
      ]},
    ],
  },
]
